### ISSUE TITLE
Nexus Incompatability

### ISSUE THREAD

**Issue by bgsteiner** [Valandur/Web-API#1]
Recently I tried to setup a server running Web-API and Nexus and realized that there is an issue with the two talking to each other. When running both at the same time the Web-API will only return  `{"code":404,"message":"Not Found"}` when disabling Nexus everything works fine. I'm not sure what exactly in Nexus is causing the problem I'm willing to do some testing to see if disabling features in Nexus solves the problem.

https://forums.spongepowered.org/t/atom-nexus-v1-8-5b-providing-100-essential-commands-and-features

**Comment by bgsteiner** [comment]
Nexus is on the wrong API version

**Comment by Valandur** [comment]
Interesting that it was affecting the Web-API though. Thank you for reporting!
