### ISSUE TITLE
Hook SERVER_STARTED and not only SERVER_START

### ISSUE THREAD

**Issue by oblx** [Valandur/Web-API#120]
Hi !

It could be great if there was a webhook on server _really_ started, when it says `Done`.
That way, one could have a real time status on his website.

Take care.

**Comment by Valandur** [comment]
Is the SERVER_START hook fired before the server is ready? This hook belongs to the `GameStartedServerEvent` from Sponge, so this should be when the server is started, but it might be when not all plugins are done yet. Maybe I can add a SERVER_READY hook?

**Comment by Cat121** [comment]
Well, I am not sure and I must admit that my test server is off for now.
However, SERVER_READY might be a first thing to try !

Le mar. 5 mars 2019 à 13:55, Marco (Valandur) <notifications@github.com> a
écrit :

**Comment by Klairm** [comment]
As long as I know, at least for me the SERVER_START hook is fired when the server is indeed ready

**Comment by oblx** [comment]
This is not an issue anymore, I should have closed it years ago 😹

**Comment by oblx** [comment]
This is not an issue anymore, I should have closed it years ago 😹
