### ISSUE TITLE
speed up the restful response

### ISSUE THREAD

**Issue by jstony** [Valandur/Web-API#121]
I'm using web-api to teach python programing for k-12.  But i found the api server too slow to respon the request. With my desktop pc(i5, 16g ram), it spand 1 sec to resp the /player or /world api. When i process 100 loops to change blocks in the world, it's need 2mins to finish. How can i speed up this? Pls ignore my pool english;)

**Comment by Cat121** [comment]
I have 3 differents setup : distant server running debian and local server running windows.

Response time is always under 50ms on distant server, there is often a lag before executing a request on windows.

My 2 cents, I hope it will help !

**Comment by jstony** [comment]
Thanks for your reply and i test on centos 7, it's less 50ms to response.

**Comment by Cat121** [comment]
Maybe ticket can stay opened (or reopened) to improve performances on windows. Let the master chose 😄

**Comment by Valandur** [comment]
Thanks for reporting this. I'm not 100% sure whats going on here to be honest. I locally test on windows too, but I've never done any actual stress or timing tests.

When you say 100 loops to change blocks are you referring to the block operations endpoint?

I would like to keep this open and see what I can figure out

**Comment by sfxworks** [comment]
Node versions the same?
Processors/server spec the same?
Overhead the same?
So many factors to just blame WebAPI here

**Comment by Cat121** [comment]
I agree with that, this ticket is a long time issue to resolve.

When I have my new webapi setup, I will put more info, *jstony
<https://github.com/jstony>* is surely going to help when he can. Let's
make webapi a better educational tool :D

Le lun. 7 janv. 2019 à 13:16, Samuel Walker <notifications@github.com> a
écrit :

**Comment by jstony** [comment]
![mc2](https://user-images.githubusercontent.com/115739/50874698-0cdee300-1400-11e9-9101-78d1bd227dfa.png)

This ticket can be close now. I'm switch the http request lib from myself to webapi-client-python and test the 100 loops with windows 10 and centos7. It seems all ok.

**Comment by Cat121** [comment]
Thanks for the tip !

Suggestion : allow users to easily configure their custom proxy solution.

I used to replace internal webserver of dynmap as well. Pepperidge farm guy remembers.
