### ISSUE TITLE
[webapi]: 172.16.0.1 sent X-Forwarded-For header, but is not a proxy. Header will be ignored!

### ISSUE THREAD

**Issue by AlienXAXS** [Valandur/Web-API#129]
Hi again,
I'm using Snort to run a reverse proxy to gain access to the Web-API control panel behind a human-friendly FQDN, however each request the website does causes this warning to print to the console.

Is there any way to prevent this from being spammed to the console?
![image](https://user-images.githubusercontent.com/1773445/62882484-e54f5080-bd29-11e9-82ec-da2f3c5be483.png)

**Comment by Valandur** [comment]
In the `config/security.conf` file you can add the reverse proxy (`172.16.0.1` in this case) to the `allowedProxies` list.

**Comment by AlienXAXS** [comment]
Hi,
Thanks for the rapid response.

I found the config value allowedProxies inside permissions.conf and ran /sponge plugins reload, the warning message has since stopped.

Thanks again.
