### ISSUE TITLE
What's the different between "webapi-5.4.6-S7.2.0.jar" & "webapi-server-5.4.6-S7.2.0.jar" ?

### ISSUE THREAD

**Issue by luochen1990** [Valandur/Web-API#139]
Hello, I'm running a sponge server at the first time, and I think this plugin will be very useful for me, but when I attempt to install this plugin, I'm confused by these two jar files:

- webapi-5.4.6-S7.2.0.jar
- webapi-server-5.4.6-S7.2.0.jar

Since I'm running a server, so I think maybe I should use the second one, but I find that only the first one is uploaded to [ore](https://ore.spongepowered.org/Valandur/Web-API), that implies that many people only use the first one, so I really don't know which one to use, and I have read all the README and find nothing about it. could you please help me?

**Comment by oblx** [comment]
Hello, you need the first one :) `webapi-server-5.4.6-S7.2.0` is made for advanced use and you already have a lot to do with the basic `webapi-5.4.6-S7.2.0` .

Have fun !

**Comment by luochen1990** [comment]
@oblx thanks for your quick reply, this is very helpful 👍
