### ISSUE TITLE
Disable output shown in console

### ISSUE THREAD

**Issue by realKSMC** [Valandur/Web-API#14]
Is there any way to disable that the result of an command request is shown in console, too?
If not, pls add :)

**Comment by Valandur** [comment]
Are you referring to requests to the `/cmd` endpoint?

**Comment by realKSMC** [comment]
Yes

**Comment by realKSMC** [comment]
Using ur commands.js from `https://github.com/Valandur/Web-API/blob/master/docs/CONSUME.md`

**Comment by Valandur** [comment]
This will be in the next release! :+1:
