### ISSUE TITLE
PDF or markdown docs ?

### ISSUE THREAD

**Issue by KaKi87** [Valandur/Web-API#144]
Hello,

The API web documentation page is crashing my browser, would it be possible to have a static version, possibly in PDF or markdown ?

Thanks

**Comment by oblx** [comment]
Uploaded one version here, it's 114Mb big however : http://www.royalcraft.fr/docs/webapi.pdf

(sry for GET /players, I didn't know about that :x )

**Comment by KaKi87** [comment]
Thanks, actually I also was able to generate a PDF using [this tool](https://www.swdoc.org/). :)

**Comment by oblx** [comment]
You made it a better way !
Hence your knowledge of docs :D
