### ISSUE TITLE
Could not pass DestructEntityEvent

### ISSUE THREAD

**Issue by oblx** [Valandur/Web-API#147]
Hi !

Lately my production server (debian 10) went mad with this reccurent error : https://pastebin.com/vvQnUvJj sorry for bad formatting)

I am running `spongevanilla-1.12.2-7.3.0` with `webapi-5.4.6-S7.2.0` and `openjdk 1.8.0_292`. The weird part is that I can't reproduce it on my local windows server, nor with an admin account.

Sometimes a MessageChannelEvent is not catched too but according to stack trace it seems to come from ultimatechat.

I disabled almost everything in servlets.conf

Any idea of the why ? I can provide more details regarding configuration.

**Comment by Valandur** [comment]
Hi!

I haven't maintained this library in quite a while, so I'm not sure I can really help you with your issue.

Quickly looking at the error message it looks like something within the SpongeAPI changed - is it possible that you're using different Sponge versions when running it locally?

I'm currently working on a rewrite of the Web-API that will also work with Forge and Spigot. If you can tell me your most important endpoints that you're using I can prioritize those and make sure to get a working verison out soon-ish. That version would work with Sponge 8, if that's your ultimate goal.

**Comment by oblx** [comment]
Hi, thanks for your quick answer :)

I set up the exact same server locally and error occured, it might be related to sponge api then.

Currently I use command and interactive-messages. Also could it be possible to disable doc module ?

I am not in a hurry for api8 but it's awesome that you are working on it. You rock :D
