### ISSUE TITLE
Add coordinates to /block endpoint output

### ISSUE THREAD

**Issue by realKSMC** [Valandur/Web-API#16]
Currently u get...

```
          {
            "type": "minecraft:air",
            "data": {}
          }
```

...as output if u ask for which block is at e.g. 100 100 100. It would be better if the output includes the coordinates too, for example when requesting an area of coordinates.

So the output looks like:

```
          {
            "type": "minecraft:air",
            "coordinates": "100, 100, 100",
            "data": {}
          }
```

**Comment by realKSMC** [comment]
Any idea when its done? :) Can't wait for it :P

**Comment by Valandur** [comment]
Implemented in https://github.com/Valandur/Web-API/commit/b6c1ddf3a70d02463fca033347f37f8bb8377c52
