### ISSUE TITLE
List players when /list

### ISSUE THREAD

**Issue by realKSMC** [Valandur/Web-API#19]
Using ur default /list command shows just the amount of players, but the typical command shows the amount + one line per each player with its name.

**Like:**

```
[14:11:11] [pool-2-thread-41/INFO]: There are 1/100 players online.
[14:11:11] [pool-2-thread-41/INFO]: Itzme
```

Pls add this to the output ;)

**Comment by realKSMC** [comment]
It was bc the WaitTime was set too low. 1s is just to less :)

**Comment by Valandur** [comment]
I would suggest using the `/player` endpoint to get the online players.

Or you can also use the `waitLines` property and wait for 2 lines, if the message is always sent on two lines.

**Comment by realKSMC** [comment]
Per player one line btw :)

I'll give `/player` a try, thx :P
