### ISSUE TITLE
[Suggestion] Access commands and execute then a new one

### ISSUE THREAD

**Issue by yololetsplay** [Valandur/Web-API#3]
Hey,

is it possible to do the following:

**In console:**
`Tester123 ran the command: /reborn`

**The plugin listen for:**
`$player ran the command: /reborn`
You defined that listening in config before.

If it found that command it **runs in server console**:
`/gm Tester123 0`

And ingame it does not say "unknown command", it says "[WEB] Running command."

The possibilities are INFINITE ;]
Best would be to support multiple server commands.
It's the easiest way to create CUSTOM COMMANDS.

**In config it could be like:**

```
listen {
$player ran the command: /reborn {
/gm 0 $player
/say $player reborned
},
$player ran the command: /godlike {
/god $player
}
}

```

Greetz,
Hannes

**Comment by yololetsplay** [comment]
Also to improve config and prevent from specific users:

**config.conf**
```
listen {
$player ran the command: $command {
/reborn {
{
permission = "web.cmd.reborn"
}
{
position
{
X,
Y,
Z,
radius
}
/gm 0 $player
/say $player reborned
},
/godlike {
/god $player
}
}
```

**Comment by yololetsplay** [comment]
If permission and/or position is not set so it's not needed to run the command.

**Comment by yololetsplay** [comment]
Finally ingame shown for useR:
`[WEB] Execute /reborn`

Your plugin will be the best for sponge!

**Comment by Valandur** [comment]
Although this is a very interesting idea, I don't think it's in the scope of this project/plugin.
To me this sounds more like a plugin by itself. I suggest posting that idea [here](https://forums.spongepowered.org/c/plugins/plugin-requests) so that someone might pick it up and make a plugin.

**Comment by tridaak** [comment]
What you would need is [command kits](https://forums.spongepowered.org/t/command-kits-v1-2-0-kits-of-commands-and-items/10270/) to make a custom set of commands. Then use [aliases](https://ore.spongepowered.org/me4502/Aliases) to create custom command aliases.

**Comment by yololetsplay** [comment]
Hey mate :)
With the current version it's now possible, am I right wich that?

Greetz,
Hannes

**Comment by yololetsplay** [comment]
@tridaak thx for the advice. Can I setup permissions with that plugin too?
