### ISSUE TITLE
Add response code 200 instead of ok

### ISSUE THREAD

**Issue by Cat121** [Valandur/Web-API#38]
When a request is sent, web api response is : 
`{"ok":true}`

However, when it's not ok, we get this : 
`{"code":400,"message":"Invalid message"}`

Is it possible to "harmonize" with code response ?
e.g. for a successful request : 
`{"code":200,"message":"ok"}`

**Comment by Valandur** [comment]
so the way this is done is that the http response code will tell you if the request was sucessful. depending on what you're using for your client, in js something like `response.statusCode`.
if the code is not 200 or 201, then the request failed, with the usual http status codes (400 inavlid request, 404 not found etc.)
if the response code is 200 or 201 then the request was successful, then the `ok` will tell you if the data was processed correctly (this should almost never fail)

**Comment by Cat121** [comment]
Oh, I got it.
Well, I will stay with `$response->ok` and I might update to http response later !
