### ISSUE TITLE
[webapi]: 127.0.0.1 does not have permission to access /api/servlet

### ISSUE THREAD

**Issue by mpowerek** [Valandur/Web-API#39]
Where is the login and password for web admin. Panel giving me information: Invalid username or password. What login and password should I use to log in

**Comment by Valandur** [comment]
you can use the command `webapi user add [username] [password]` to add a new user.

for example `webapi user add admin password` will add user `admin` with password `password`

**Comment by Valandur** [comment]
I apologize that this is not documented yet, will add it as soon as possible

**Comment by mpowerek** [comment]
Thanks for very very speed support.

**Comment by mpowerek** [comment]
[Server thread/INFO]: Input command user was not a valid subcommand!
user add admin password

**Comment by mpowerek** [comment]
Where do i have to put this command?

**Comment by mpowerek** [comment]
Nevermind. It's bad command.
It isn't "webapi user add admin password"
It is "webapi userS add admin password"

**Comment by mpowerek** [comment]
Can i change password?

**Comment by Cat121** [comment]
You can do this in console :  
`webapi users password <username> <newpassword`

**Comment by mpowerek** [comment]
thx <3
