### ISSUE TITLE
Multiple call

### ISSUE THREAD

**Issue by ArcasCZ** [Valandur/Web-API#4]
Is there any way to make request with multiple commands and get all responses?

**Comment by Valandur** [comment]
There currently isn't, no, but I could add it.
Is there any specific reason why you can't use multiple API calls tough?

**Comment by ArcasCZ** [comment]
It's faster and that's what I need, 'cause I have limited PHP processes and execute time.

**Comment by Valandur** [comment]
This is going to be in the next release 😃

**Comment by ArcasCZ** [comment]
Great :-)

**Comment by Valandur** [comment]
Implemented in https://github.com/Valandur/Web-API/releases/tag/v2.0, but that is still an alpha release so please use with caution. Parts of the API also changed.

**Comment by Valandur** [comment]
I'm going to close this as v2 is now a stable release. Thanks for the input.
