### ISSUE TITLE
Order options for interactive messages

### ISSUE THREAD

**Issue by Cat121** [Valandur/Web-API#41]
Whenever I send a similar request X times, options can get a different order.

Request is : 
`{"id":"shulker","target":"df0f36a7-f819-4884-9120-77a7b942349d","message":"Coffre inconnu, dans quel groupe faut-il l'ajouter ?","once":true,"options":{"Derinku-18-3":"\u00a7a[Derinku]","Forlonde-18-2":"\u00a7c[Forlonde]","Masdar-18-1":"\u00a76[Masdar]","Ringuith-18-4":"\u00a7b[Ringuith]"}}`

Ingame result after sending it 5 times : https://imgur.com/tS3k2jV

Readable json request : https://imgur.com/iNV9EUW
(using http://json.parser.online.fr/)

**Comment by Valandur** [comment]
Fixed in 1055a1363a47afac1cb2d41a3345b781651b9d16
