### ISSUE TITLE
Add GET/PUT endpoint for chests and shulkers

### ISSUE THREAD

**Issue by Cat121** [Valandur/Web-API#42]
As of now, we can get a block informations like this : 

```
{
    "ok": true,
    "position": {
        "x": 2263,
        "y": 53,
        "z": -2852
    },
    "block": {
        "type": "minecraft:chest",
        "data": {
            "facing": "WEST"
        }
    }
}
```

But there is no way to get/set content of a container. Could it be possible to add it ? Including shulker boxes.

Maybe by adding additionnal flags like : 

    "block": {
        "type": "minecraft:chest",
        "container": "true",
        "data": {
            "facing": "WEST"
        },
        "content": {
            0: "json of object slot 0 (lore, enchants, name, durability, etc)",
            1: "json of object slot 1",
            2: "json of object slot 2",
            (etc...)
        }
    }

And we could PUT content with slot:item, these two requests would update chest fully or partially : 

```
        "content": {
            0: "", // Set slot 0 to nothing
            1: "json of object slot 1", //Set slot 1 to item json
            2: "json of object slot 2", //Set slot 2 to item json
            (etc...)
        }
```

```
        "content": {
            1: "", // Doesn't change slot 0 and set slot 1 to nothing
            2: "json of object slot 2", Set slot 2 to item json
            (etc...)
        }
```

I might give more details if it's not clear !

**Comment by Valandur** [comment]
GETing the contents is already possibly, but you have to use the `/tile-entity` endpoint for this, as blocks only store very basic information like type and rotation, everything else is saved on the tile entities.

PUTing is not yet possible, but I'm working on that for the next build, which should be released soon

**Comment by Cat121** [comment]
I was not sure if entities could do the trick but yes they do. Thanks, I still didn't have time to try redprotect endpoints !
