### ISSUE TITLE
Instructions to provide custom servlets?

### ISSUE THREAD

**Issue by ryantheleach** [Valandur/Web-API#43]
Do you think you could have some documentation / a section on other plugins providing servlets?

**Comment by Valandur** [comment]
This has been added in release [4.7.0](https://github.com/Valandur/Web-API/releases/tag/v4.7.0) and can be found [here](https://github.com/Valandur/Web-API/blob/master/docs/API.md)

**Comment by ryantheleach** [comment]
Thanks!

**Comment by Valandur** [comment]
I will close this issue for now, if you need further info/documentation don't hesitate to contact me here or on the sponge forums!
