### ISSUE TITLE
Not able to add permission for custom commands

### ISSUE THREAD

**Issue by Cat121** [Valandur/Web-API#45]
In hooks.conf I registered : 

command {
    bookmenu {
        aliases=[
            menu,
            mn
        ]
        enabled=true
    }
}

But players with permission `webapi.command.notify.bookmenu` get "you don't have permission to use this command".

I also tried with permission `webapi.command.notify.menu`

Did domething change with latest update ?

**Comment by Valandur** [comment]
I believe the permission is `webapi.notify.bookmenu`. The documentation is probably wrong again :(

**Comment by Cat121** [comment]
Yeah, that was it, I change it on documentation !
