### ISSUE TITLE
Error on starting v4.7.2 with API 6.1

### ISSUE THREAD

**Issue by Cat121** [Valandur/Web-API#47]
Latest build fixed the bug on docs and admin panel, it's now an other one that occurs : https://imgur.com/l9NuqmV

Custom code is : 

```
custom {
    # _EXAMPLE_
    "io.github.nucleuspowered.nucleus.api.events.NucleusAFKEvent"=[
        {
            address="https://api.royalcraft.fr/custom"
            dataType=JSON
            details=false
            enabled=true
            form=true
            method=POST
            permissions="*"
        }
    ]
}
```

**Comment by Valandur** [comment]
What version of nucleus are you using?

**Comment by Cat121** [comment]
Woop, I forgot to include Nucleus on my test server :x 
Solved problem !

Also, you have a pending pull on documentation.
