### ISSUE TITLE
Web-Api VPS

### ISSUE THREAD

**Issue by WareZ57** [Valandur/Web-API#51]
Hello I would like to know if there is possibility to install web API on a full web server where am I obliged to use the server localhost ?

Thanks You.

**Comment by Valandur** [comment]
Currently Web-API only runs on the server where your minecraft server is running. But you can run the rest of your website on a webserver and have it interact with the Web-API.

I'm not quite sure I understood your question correctly, I hope the above answers it. If not please let me know.

**Comment by WareZ57** [comment]
Thank you for your reply (sorry for my bad english) it's ok thanks you so much ! 👍

**Comment by Valandur** [comment]
I will close this in favour of the referenced issue, and provide updates in that discussion when I have news about multi-server/external webserver support.
