### ISSUE TITLE
[REQUEST] Use external web server

### ISSUE THREAD

**Issue by LiskoSlayer63** [Valandur/Web-API#52]
Is it possible to make this run on an external web server like DynMap does? I mean that if I have a web server installed like IIS, then I would use it rather than make the Minecraft to host it's own server.

**Comment by Valandur** [comment]
The problem with this is that Web-API provides actual code which is executed, and not just static files that are served like DynMap does.  

I believe this might be possible if I change the Web-API to be just a Jetty/JSP-Servlet, but then you would still have to find a way to run a Jetty/JSP servlet from IIS, maybe according to [this](https://stackoverflow.com/a/32172814) or [this](http://www.helicontech.com/articles/deploying-java-servlet-applications-on-windows-with-iis/).  

The other option would be to [use IIS as a proxy to redirect to Jetty](https://myadventuresincoding.wordpress.com/2015/01/11/iis-setup-iis-as-a-proxy-to-jetty/). Although this is not that nice as you're still running two web servers, you can run the jetty server only on localhost to hide it from the public. This solution would work with the current Web-API version.

**Comment by Valandur** [comment]
I will close this in favour of the referenced issue, and will keep posting in that issue when I have updates on the progress of multi server/external webserver support
