### ISSUE TITLE
commands filter

### ISSUE THREAD

**Issue by ziceptor** [Valandur/Web-API#55]
I would like to exclude some commands from the log. Is this possible?

**Comment by Valandur** [comment]
Do you mean in the server console?  
That's currently not possible, unless you use some kind of log filter plugin, but I can add that to the next version.

**Comment by ziceptor** [comment]
Commands executed from the client. From the chat room.

**Comment by Valandur** [comment]
Are you talking about commands like `/webapi notify` or `/webapi users add ...`?  
Why would you want to hide those?

**Comment by ziceptor** [comment]
I wouldn't want in admin interface to display data input user /pass reg pass and log /pass (flexiblelogin). This can be a problem when hacking the admin.

**Comment by Valandur** [comment]
Ah ok I see what the issue is. Yes I can add that, no problem. Will be in the next version!
