### ISSUE TITLE
Hide command in console

### ISSUE THREAD

**Issue by realKSMC** [Valandur/Web-API#58]
## Question
Is it even possible to hide it in console when executing an command, maybe something I can add to my .js?

**Comment by Valandur** [comment]
Not sure if this is possible, I will have a look!

**Comment by realKSMC** [comment]
Thx :)

**Comment by Valandur** [comment]
Have you tried doing `hideInConsole: true`?

**Comment by realKSMC** [comment]
Works great :)

**Comment by realKSMC** [comment]
I just oversaw it: Still the same output than before. E.g. `[19:24:05] [Server thread/INFO]: [Decayworld: Block placed]
`

**Comment by Valandur** [comment]
What endpoint are you using that generates this output? The /ops endpoint? Or are you doing something from the AdminPanel?
