### ISSUE TITLE
Sometimes missing Content-Type header

### ISSUE THREAD

**Issue by jkroepke** [Valandur/Web-API#59]
Hi,

sometimes, the files served from the WebAPI doesn't have a Content-Type header.

If 'X-Content-Type-Options: nosniff' is present in the html response, the WebAPI won't loading correctly.

**Comment by Valandur** [comment]
Thank you for reporting this, I will look into it. Do you have more information about what files?  
And what do you mean if the header is in the response? You mean if it's in the request?

**Comment by jkroepke** [comment]
> Do you have more information about what files?
Any file request on first time (after starting the server)
> And what do you mean if the header is in the response?
Reponse Header.

First Request:
<img width="1440" alt="bildschirmfoto 2018-01-27 um 19 48 34" src="https://user-images.githubusercontent.com/1560587/35475265-9d7e45a2-039b-11e8-904c-7fd809b54f81.png">

Second Request:
<img width="1440" alt="bildschirmfoto 2018-01-27 um 19 48 47" src="https://user-images.githubusercontent.com/1560587/35475266-9d94685a-039b-11e8-9ee3-5c47e8798d5b.png">

Console Errors:

<img width="1440" alt="bildschirmfoto 2018-01-27 um 19 50 31" src="https://user-images.githubusercontent.com/1560587/35475268-9db1311a-039b-11e8-8196-674ba09c0f28.png">
