### ISSUE TITLE
Option to enable/disable parts of Server Settings in config

### ISSUE THREAD

**Issue by realKSMC** [Valandur/Web-API#62]
## Request
Related to the admin-panel: Pls add that each part of the Server Settings can be enabled or disabled in config. I would like to host an server for some friends, but they should e.g. not be able to change the `max-players`, `server-ip`, `view-distance` and `server_port`.

**Comment by Valandur** [comment]
Very nice idea, I will include that 👍

**Comment by realKSMC** [comment]
When do you release it? Can't wait for it :)

**Comment by Valandur** [comment]
Its currently in the v5 branch. If I'm able to finish v5 by the end of the week it'll be released with it, if not I will make a separate release for it - so either way by the end of this week :) sorry for the delay

**Comment by realKSMC** [comment]
Absolute no problem, I am just happy u release it asap :)

**Comment by realKSMC** [comment]
Well, what about the update? I saw there was an new release, is this included?

**Comment by Valandur** [comment]
Yes, this is implemented and available in [v5.0.2](https://github.com/Valandur/Web-API/releases/tag/v5.0.2), I forgot to mention this issue in the commit message, so it didn't auto close.

**Comment by realKSMC** [comment]
Where can I edit it in config? :)

**Comment by Valandur** [comment]
I'm sorry, I never saw this reply for some reason. I would suggest you join [the discord server](https://discrod.gg/ReTHwNE) for support, I'd love to help you there :)
I'll go ahead and close this issue. Sorry again for not replying, I just saw your response
