### ISSUE TITLE
Can't POST Request to API Server Plugin

### ISSUE THREAD

**Issue by pdglobal** [Valandur/Web-API#64]
Please help, I am trying to send a POST request to the API to execute the command:

"broadcast test message"

See my simple php code below, It's authenticating but returning the following error:

> {"code":400,"message":"Invalid command data: Cannot deserialize instance of `java.lang.String` out of START_ARRAY token\n at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: valandur.webapi.serialize.request.command.ExecuteCommandRequest[\"command\"])"}

Code:
```
<?PHP
_postdata('http://127.0.0.1:8080/api/cmd', array("command" => "broadcast test message"), array('x-webapi-key: HIDDEN))
function _postdata($url, $data, $header) {
    $curl = curl_init($url);
	curl_setopt($curl,CURLOPT_HTTPHEADER, $header);
    curl_setopt($curl, CURLOPT_POST, true);
    curl_setopt($curl, CURLOPT_POSTFIELDS, http_build_query($data));
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
    $response = curl_exec($curl);
    curl_close($curl);
    return $data.'=>'.$response;
}
?>
```

Please help, it would only take a moment of your time and would help me greatly.

**Comment by Valandur** [comment]
Hi :) If you're looking for support and quick replies you're usually better off on [discord](https://discord.gg/ReTHwNE) or the Sponge forums, Github is meant for issues.

Concerning this issue - This actually seems to be a bug, or rather an inconsistency.
As a quick fix I would recommend you change your code to the following:
```php
<?PHP
_postdata('http://127.0.0.1:8080/api/cmd', array("command" => "broadcast test message"), array('x-webapi-key: HIDDEN'));
function _postdata($url, $data, $header) {
	$header[] = 'Content-Type: application/json';
	$curl = curl_init($url);
	curl_setopt($curl,CURLOPT_HTTPHEADER, $header);
	curl_setopt($curl, CURLOPT_POST, true);
	curl_setopt($curl, CURLOPT_POSTFIELDS, json_encode($data));
	curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
	$response = curl_exec($curl);
	curl_close($curl);
	return $data.'=>'.$response;
}
```
> **$header[] = 'Content-Type: application/json';**  

makes sure that the request is understood as json by the server and  

> curl_setopt($curl, CURLOPT_POSTFIELDS, **json_encode($data)**);

sends the request as a json request

**Comment by pdglobal** [comment]
Thanks so much my man! I'll make sure to ask for help in the forums or discord from now on, just wasn't sure where to go for help. Also, is there a feature in webapi to send a message to the whole server without having to call the broadcast command?(so that [broadcast] doesnt't show up in front of the message) If not, could I kindly request you add this functionality? It would be super useful for a variety of reasons.

**Comment by Cat121** [comment]
You might use `say` command as well. I have no `[broadcast]` tag when using `broadcast`.

``` php
					// Open menu and broadcast the stuff
					$commandArgs = array(
						array(
							'name'      => COMMAND_USER,
							'command'   => 'broadcast ' . $player->getVal('name') . ' vient de finir la quête de départ !'),
						array(
							'name'		=> $player->getVal('name'),
							'command'	=> 'webbook ' . APIURL . '/webbook ' . $player->getVal('name'))
					);

					$api->setArgs($commandArgs);
					$api->setEndpoint('cmd');
					$api->buildRequest();
					$api->execute();
```

**Comment by Valandur** [comment]
The ability to send an interactive messages to the whole server was added in [v5.0.2](https://github.com/Valandur/Web-API/releases/tag/v5.0.2)
