### ISSUE TITLE
Enable IP ranges in allowed proxies

### ISSUE THREAD

**Issue by pdglobal** [Valandur/Web-API#65]
Please enable the ability to specify ip ranges in the allowed proxy ips sections, this is so that we can use cloudflare without having to manually list hundreds of ips 1 by 1 to prevent console spam(or better yet add the option to disable console alerts about unauthorized proxy, or both)

**Comment by Valandur** [comment]
Nice suggestion. Were you thinking of IP ranges in the style of IP blocks `148.20.57.0/29` or differently?

**Comment by pdglobal** [comment]
Yes I was thinking exactly that. Especially considering that's how most IP ranges are represented and it's a very compact format.
