### ISSUE TITLE
Different json output for webhooks with or without details option

### ISSUE THREAD

**Issue by Cat121** [Valandur/Web-API#66]
So I have : 
```
    "player_join"=[
        {
            address="myurl"
            dataType=JSON
            details=false
            enabled=true
            form=true
            method=POST
            permissions="rcapi.login"
        }
    ]
```
https://imgur.com/rmGXAut

However, if I set details=true, json output doesn't include data object : 
```
    "player_leave"=[
        {
            address="https://api.royalcraft.fr/logout"
            dataType=JSON
            details=true
            enabled=true
            form=true
            method=POST
            permissions="rcapi.logout"
        }
    ]
```
https://imgur.com/Arxrh3d

Which is not convenient to change code whenever I need details or not.

**Comment by Cat121** [comment]
Tested a few minutes ago with 4.10.6-S6.1 and bug still happens.

details=false : 
```
{
    "data":{},
    "class":"org.spongepowered.api.event.ClientConnectionEvent$Join$Impl"
}
```

details=true
```
{
    "class":"org.spongepowered.api.event.ClientConnectionEvent$Disconnect$Impl",
    "cause":{},
    "target":{
        "id":"df0f36a7-f819-4884-9120-77a7b942349d",
        "name":"Keuterio"
    }
}
```

**Comment by Valandur** [comment]
Its fixed in version 5+, but I didnt backport that version to Sponge 6 or 5 yet. Do you have the possibility of switching to v5?

**Comment by Cat121** [comment]
Well, I am still using API6 but I might consider switching to API7 if you don't plan to support older versions of sponge.

I can also change my code with 4.10
