### ISSUE TITLE
Broadcast chat interface. 

### ISSUE THREAD

**Issue by pdglobal** [Valandur/Web-API#68]
Looking for the ability to broadcast a message to whole server for integrating web chat room with server chat. Please advise if you could add this functionality.

**Comment by Valandur** [comment]
This is most likely related to the last comments in #64  

You have the option of either using the `/cmd` endpoint with a `broadcast` command, or you can use the `/cmd` endpoint with a `say` command. In both cases I would recommend setting the `name` parameter, which sets the "sender" of the command.

I have added the ability to send interactive messages to the whole server (as of version 5.0.0 [not yet released]), so you could also use the `/interactive-message` endpoint once version 5 is released.

**Comment by Valandur** [comment]
The ability to send an interactive message to all online players was added in [v5.0.2](https://github.com/Valandur/Web-API/releases/tag/v5.0.2)
