### ISSUE TITLE
I create the user but cannot login adminpanel

### ISSUE THREAD

**Issue by Moeblack** [Valandur/Web-API#93]
I can enter the url like http://localhost:8080/admin/login but cannot login with correct username and passwd. There is "login error" in red

**Comment by Valandur** [comment]
Does the minecraft console show an error? Did you whitelist the ip from where you're trying to connect? Maybe try `/webapi whitelist add 127.0.0.1`. Is the minecraft server running on your own computer?
If you want faster help it you can contact me on discord @ Valandur#3581 or [join the support discord](https://discord.gg/ReTHwNE)
